### ISSUE TITLE
 panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by matthiasbeyer** [gyscos/Cursive#111]
Hi,

I ran into:

```
thread 'main' panicked at 'attempt to subtract with overflow', /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/views/list_view.rs:229
stack backtrace:
   1:     0x7fc581953f6c - std::sys::imp::backtrace::tracing::imp::write::hdc68b25dedcd1db8
   2:     0x7fc581952a7e - std::panicking::default_hook::{{closure}}::h5edd4f46e38f8310
   3:     0x7fc581952763 - std::panicking::default_hook::hda32855a02198554
   4:     0x7fc581952f0b - std::panicking::rust_panic_with_hook::hdd2e2d2d6c308562
   5:     0x7fc581952d54 - std::panicking::begin_panic::h48ad6352979e67f1
   6:     0x7fc581952cc9 - std::panicking::begin_panic_fmt::h2ded1b6830a36623
   7:     0x7fc581952c57 - rust_begin_unwind
   8:     0x7fc5819b1d6d - core::panicking::panic_fmt::h2aae0852c2562c9f
   9:     0x7fc5819b1ca4 - core::panicking::panic::h7f49eacfb0b4c1fc
  10:     0x55ec0df23aa8 - <cursive::views::list_view::ListView as cursive::view::View>::layout::h68ec5254d2a965f7
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/views/list_view.rs:229
  11:     0x55ec0de98ccc - cursive::view::view_wrapper::ViewWrapper::wrap_layout::h9e9d7de1055dca60
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/view/view_wrapper.rs:45
  12:     0x55ec0de9aa7f - cursive::view::view_wrapper::<impl cursive::view::View for T>::layout::h0437efaaaa52fd53
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/view/view_wrapper.rs:78
  13:     0x55ec0de98dac - cursive::view::view_wrapper::ViewWrapper::wrap_layout::hdeb15779bd802288
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/view/view_wrapper.rs:45
  14:     0x55ec0de9abff - cursive::view::view_wrapper::<impl cursive::view::View for T>::layout::had410b533505ca6d
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/view/view_wrapper.rs:78
  15:     0x55ec0df208ce - <cursive::views::linear_layout::LinearLayout as cursive::view::View>::layout::he430049eeb1c48a1
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/views/linear_layout.rs:201
  16:     0x55ec0de98bec - cursive::view::view_wrapper::ViewWrapper::wrap_layout::h5b2fd4995ac90378
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/view/view_wrapper.rs:45
  17:     0x55ec0de9acbf - cursive::view::view_wrapper::<impl cursive::view::View for T>::layout::hc245bd8e062c3d60
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/view/view_wrapper.rs:78
  18:     0x55ec0de64ad4 - <cursive::views::shadow_view::ShadowView<T> as cursive::view::view_wrapper::ViewWrapper>::wrap_layout::he941d882bcdabd4d
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/views/shadow_view.rs:58
  19:     0x55ec0de9ab9f - cursive::view::view_wrapper::<impl cursive::view::View for T>::layout::h7bb1fefbf58cdf4a
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/view/view_wrapper.rs:78
  20:     0x55ec0df29ed9 - <cursive::views::stack_view::StackView as cursive::view::View>::layout::h7de8e74d223fe846
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/views/stack_view.rs:154
  21:     0x55ec0df356ba - cursive::Cursive::layout::h593ae75221da9ba7
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/lib.rs:494
  22:     0x55ec0df35df5 - cursive::Cursive::step::hc789d40ea1a7d171
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/lib.rs:570
  23:     0x55ec0df35c8f - cursive::Cursive::run::ha463ea6606b82047
                        at /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.4.1/src/lib.rs:552
  24:     0x55ec0deae19f - rikki::frontend::curses::start::h0dcd081ef2d42d16
                        at /home/m/archive/code/rust/rikki/src/frontend/curses/mod.rs:38
  25:     0x55ec0deae761 - rikki::main::heea4d07080c68991
                        at /home/m/archive/code/rust/rikki/src/main.rs:84
  26:     0x7fc581961567 - __rust_maybe_catch_panic
  27:     0x7fc58195b667 - std::rt::lang_start::h667ad30118861e80
  28:     0x55ec0deb3a12 - main
  29:     0x7fc57fa2752f - __libc_start_main
  30:     0x55ec0de62759 - _start
                        at ../sysdeps/x86_64/start.S:120
  31:                0x0 - <unknown>
```

Anything I can do about it?

**Comment by matthiasbeyer** [comment]
This happens (as it seems) if the terminal window is too small ...

**Comment by gyscos** [comment]
Indeed, `ListView` wasn't properly defensive with regard to small viewports. Working on a fix.
Thanks for the report!

**Comment by gyscos** [comment]
Should be fixed in 7d9cb03ffbfeeeac2e02adce2b4139a62fc5d31c.

**Comment by simmons** [comment]
For what it's worth, I'm also seeing an "attempt to subtract with overflow" on the latest master commit 5f5fb4e when I try to wrap a SelectView in a Panel (in a BoxView in a LinearLayout).  It looks like it's happening where Panel is trying to make room for a border in Panel.wrap_required_size().  (But it's a fair likelihood that I'm just misunderstanding something about view arrangement.)

```rust
extern crate cursive;
use cursive::Cursive;
use cursive::view::*;
use cursive::views::*;
fn main() {
    let mut siv = Cursive::new();
    let mut select_view = SelectView::new();
    select_view.add_item("Item 1", 1);
    select_view.add_item("Item 2", 2);
    let body = BoxView::new(
        SizeConstraint::Full,
        SizeConstraint::Full,
        Panel::new(select_view)
    );
    let status = BoxView::new(
        SizeConstraint::Full,
        SizeConstraint::Fixed(1),
        TextView::new("status line")
    );
    let layout = LinearLayout::vertical()
        .child(body)
        .child(status);
    siv.add_layer(layout);
    siv.run();
}
```

**Comment by gyscos** [comment]
Indeed, that was a bug in `Panel` - thanks! Should be fixed in 87676295a0d79d57a660ebbc9490abcb74f04c4c.

**Comment by gyscos** [comment]
@matthiasbeyer Can you confirm your bug is fixed in latest master?

**Comment by gyscos** [comment]
I'll assume this is fixed - feel free to open it again if I'm wrong!

**Comment by vertexclique** [comment]
Currently, I get this error exactly like above stack trace with 0.9.1.
Didn't understand what caused this but if lines are long it bails out at this point.

**Comment by gyscos** [comment]
@vertexclique Interesting! Can you post a sample code to reproduce the issue?

**Comment by vertexclique** [comment]
```
PanicInfo { payload: Any, message: Some(attempt to subtract with overflow), location: Location { file: "/Users/m.bulut/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.1/src/views/list_view.rs", line: 412, col: 43 } }
```

**Comment by gyscos** [comment]
Indeed, there was an unchecked subtraction there. Should be fixed on 9b3b16f64dbcce1920f18252daa19b07ba3ad14d.

**Comment by vertexclique** [comment]
Oh, you're faster than my stack trace unwinding code :D cool… When I can use the new version?

**Comment by gyscos** [comment]
Just published 0.9.2 which should include the fix.

**Comment by vertexclique** [comment]
### Like A Boss!

![](https://media.giphy.com/media/lH831M7w8lO6I/giphy.gif)
