### ISSUE TITLE
BorrowMutError regression on 0.5.1

### ISSUE THREAD

**Issue by scottlamb** [gyscos/Cursive#144]
I upgraded [my project](https://github.com/scottlamb/moonfire-nvr) from cursive 0.4.1 to cursive 0.5.1 and broke it in the process. It's possible I'm holding it wrong, but my code worked before and doesn't now.

I boiled it down to this:

```rust
extern crate cursive;

use cursive::Cursive;
use cursive::traits::Identifiable;
use cursive::views::{Button, Dialog, DummyView, EditView, LinearLayout, ListView, TextView};

fn main() {
    let mut siv = Cursive::new();
    let list = ListView::new()
        .child("foo", EditView::new().with_id("foo"))
        .child("bar", LinearLayout::horizontal()
               .child(EditView::new().with_id("bar"))
               .child(DummyView)
               .child(Button::new("Test", |siv| {
                   let t = (
                       siv.find_id::<EditView>("foo").unwrap().get_content(),
                       siv.find_id::<EditView>("bar").unwrap().get_content(),
                   );
                   siv.add_layer(Dialog::text(format!("foo: '{}' bar: '{}'", t.0, t.1)));
               })));
    siv.add_layer(Dialog::around(list));
    siv.run();
}
```

with cursive 0.4.1, it works. with cursive 0.5.1, when I click on the "Test" button, my program dies with this backtrace:

```
thread 'main' panicked at 'already borrowed: BorrowMutError', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:761
  11: <core::cell::RefCell<T>>::borrow_mut
             at /checkout/src/libcore/cell.rs:670
  12: <cursive::views::id_view::IdView<T> as cursive::view::view_wrapper::ViewWrapper>::wrap_call_on_any
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/views/id_view.rs:69
  13: cursive::view::view_wrapper::<impl cursive::view::View for T>::call_on_any
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/view/view_wrapper.rs:94
  14: <cursive::views::list_view::ListView as cursive::view::View>::call_on_any
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/views/list_view.rs:321
  15: <cursive::views::dialog::Dialog as cursive::view::View>::call_on_any
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/views/dialog.rs:404
  16: cursive::view::view_wrapper::ViewWrapper::wrap_call_on_any::{{closure}}
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/view/view_wrapper.rs:57
  17: <cursive::views::layer::Layer<T> as cursive::view::view_wrapper::ViewWrapper>::with_view_mut
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/view/view_wrapper.rs:141
  18: cursive::view::view_wrapper::ViewWrapper::wrap_call_on_any
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/view/view_wrapper.rs:57
  19: cursive::view::view_wrapper::<impl cursive::view::View for T>::call_on_any
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/view/view_wrapper.rs:94
  20: cursive::view::view_wrapper::ViewWrapper::wrap_call_on_any::{{closure}}
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/view/view_wrapper.rs:57
  21: <cursive::views::shadow_view::ShadowView<T> as cursive::view::view_wrapper::ViewWrapper>::with_view_mut
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/view/view_wrapper.rs:141
  22: cursive::view::view_wrapper::ViewWrapper::wrap_call_on_any
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/view/view_wrapper.rs:57
  23: cursive::view::view_wrapper::<impl cursive::view::View for T>::call_on_any
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/view/view_wrapper.rs:94
  24: <cursive::views::stack_view::StackView as cursive::view::View>::call_on_any
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/views/stack_view.rs:214
  25: <T as cursive::view::Finder>::call_on
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/view/mod.rs:193
  26: cursive::Cursive::call_on
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/lib.rs:400
  27: cursive::Cursive::call_on_id
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/lib.rs:430
  28: cursive::Cursive::find_id
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/lib.rs:442
  29: broken_cursive::main::{{closure}}
             at ./src/main.rs:17
  30: cursive::Cursive::step
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/lib.rs:639
  31: cursive::Cursive::run
             at /home/slamb/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.5.1/src/lib.rs:590
  32: broken_cursive::main
             at ./src/main.rs:22
  33: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  34: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  35: main
  36: __libc_start_main
  37: _start
```

**Comment by gyscos** [comment]
Indeed! Interestingly, the temporary reference object created in `find_id` is not dropped before the second call.
