### ISSUE TITLE
Crashes with 101 return code under certain layouts

### ISSUE THREAD

**Issue by hcpl** [gyscos/Cursive#147]
### Description

For most layouts this issue is not present, but it is for some, e.g. for the one shown below.

### Configuration
```sh
$ uname -srm
Linux 4.2.0-42-generic x86_64
$ rustc --version
rustc 1.18.0 (03fc9d622 2017-06-06)
```

Cursive version 0.6.1

### Expected behaviour
Run normally

### Actual behaviour
Whole app crashes, exits ncurses mode and returns 101 code.

### Code to reproduce
```rust
extern crate cursive;

use cursive::Cursive;
use cursive::views::{BoxView, LinearLayout, TextArea, TextView};

fn main() {
    let mut siv = Cursive::new();

    let x = LinearLayout::vertical()
        .child(BoxView::with_full_screen(TextView::new("contents")))
        .child(LinearLayout::horizontal()
            .child(TextView::new("prompt"))
            .child(BoxView::with_full_width(TextArea::new().content("text to edit"))));

    siv.add_fullscreen_layer(BoxView::with_full_screen(x));

    siv.run();
}
```

**Comment by gyscos** [comment]
Indeed, `LinesIterator` wasn't being protective enough.
Thanks for the report! :)

**Comment by gyscos** [comment]
I should probably replace most/all `usize` subtractions with "safe" variants like here... It's a main source of unexpected panics.

**Comment by hcpl** [comment]
This worked for me, thanks!

**Comment by hcpl** [comment]
The slightly modified version of the code above (`Cursive::new()` replaced by `Cursive::default()` as of `cursive` 0.9.0) now is broken again:

<details>
<summary>Backtrace</summary>

```
   Compiling cursive-test v0.1.0 (file:///tmp/rust/cursive-test)
    Finished dev [unoptimized + debuginfo] target(s) in 3.96s
     Running `target/debug/cursive-test`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::panicking::panic
             at libcore/panicking.rs:53
   9: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  10: cursive::views::text_area::TextArea::row_at
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/text_area.rs:145
  11: cursive::views::text_area::TextArea::selected_row
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/text_area.rs:163
  12: <cursive::views::text_area::TextArea as cursive::view::view::View>::draw::{{closure}}::{{closure}}
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/text_area.rs:482
  13: cursive::view::scroll::ScrollBase::draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/scroll.rs:264
  14: <cursive::views::text_area::TextArea as cursive::view::view::View>::draw::{{closure}}
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/text_area.rs:472
  15: cursive::printer::Printer::with_color
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/printer.rs:265
  16: <cursive::views::text_area::TextArea as cursive::view::view::View>::draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/text_area.rs:453
  17: cursive::view::view_wrapper::ViewWrapper::wrap_draw::{{closure}}
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:54
  18: <cursive::views::box_view::BoxView<T> as cursive::view::view_wrapper::ViewWrapper>::with_view
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:175
  19: cursive::view::view_wrapper::ViewWrapper::wrap_draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:54
  20: cursive::view::view_wrapper::<impl cursive::view::view::View for T>::draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:108
  21: <cursive::views::linear_layout::LinearLayout as cursive::view::view::View>::draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/linear_layout.rs:348
  22: <cursive::views::linear_layout::LinearLayout as cursive::view::view::View>::draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/linear_layout.rs:348
  23: cursive::view::view_wrapper::ViewWrapper::wrap_draw::{{closure}}
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:54
  24: <cursive::views::box_view::BoxView<T> as cursive::view::view_wrapper::ViewWrapper>::with_view
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:175
  25: cursive::view::view_wrapper::ViewWrapper::wrap_draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:54
  26: cursive::view::view_wrapper::<impl cursive::view::view::View for T>::draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:108
  27: cursive::view::view_wrapper::ViewWrapper::wrap_draw::{{closure}}
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:54
  28: <cursive::views::view_box::ViewBox as cursive::view::view_wrapper::ViewWrapper>::with_view
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/view_box.rs:52
  29: cursive::view::view_wrapper::ViewWrapper::wrap_draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:54
  30: cursive::view::view_wrapper::<impl cursive::view::view::View for T>::draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:108
  31: <cursive::views::layer::Layer<T> as cursive::view::view_wrapper::ViewWrapper>::wrap_draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/layer.rs:30
  32: cursive::view::view_wrapper::<impl cursive::view::view::View for T>::draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/view/view_wrapper.rs:108
  33: <cursive::views::stack_view::ChildWrapper<T> as cursive::view::view::View>::draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/stack_view.rs:110
  34: cursive::views::stack_view::StackView::draw_fg::{{closure}}
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/stack_view.rs:462
  35: cursive::printer::Printer::with_color
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/printer.rs:265
  36: cursive::views::stack_view::StackView::draw_fg
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/views/stack_view.rs:457
  37: cursive::cursive::Cursive::draw
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/cursive.rs:694
  38: cursive::cursive::Cursive::step
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/cursive.rs:739
  39: cursive::cursive::Cursive::run
             at /home/hcpl/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.9.0/src/cursive.rs:721
  40: cursive_test::main
             at src/main.rs:17
  41: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  42: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  43: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  44: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  45: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  46: main
  47: __libc_start_main
  48: <unknown>
```
</details>

**Comment by gyscos** [comment]
Indeed! Thanks for the report. It should be fixed now.

**Comment by matthiasbeyer** [comment]
I managed to crash cursive with `101` still (as of cursive 0.15). My code is rather complex though, and I'm pretty sure I cannot reproduce how it crashes with simple code.

Would you care to investigate my codebase?

**Comment by gyscos** [comment]
Hi! Can you pose a stack trace?

```bash
$ export RUSTC_BACKTRACE=full
$ cargo run 2> error.txt
```

**Comment by matthiasbeyer** [comment]
Ah, that's how I can see the actual error! I found out that it was because of my own code. Thanks for your fast response!
